version: 2.1

orbs:
  orb-tools: circleci/orb-tools@9.0
  aws-cli: circleci/aws-cli@dev:alpha

# Pipeline parameters
parameters:
  # These pipeline parameters are required by the "trigger-integration-tests-workflow"
  # job, by default.
  run-integration-tests:
    type: boolean
    default: false
  dev-orb-version:
    type: string
    default: "dev:alpha"

commands:
  check-latest-version-installed:
    steps:
      - run:
          name: Check that the latest version is installed
          command: |
            aws --version
            if [ "$(pip list --outdated | grep -c "awscli")" -ge 1 ]; then
              echo "aws version is outdated"
              exit 1
            fi

jobs:
  integration-tests:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup

  test-skip-install-check:
    # This image is suitable for the test as it comes with aws preinstalled
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - aws-cli/setup:
          skip-install-check: true
      - check-latest-version-installed

workflows:
  lint-pack_validate_deploy-dev:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint

      - orb-tools/pack:
          requires: [orb-tools/lint]

      - orb-tools/publish-dev:
          context: orb-publishing
          orb-name: circleci/aws-cli
          requires: [orb-tools/pack]

      - orb-tools/trigger-integration-tests-workflow:
          context: orb-publishing
          requires: [orb-tools/publish-dev]

  integration-tests_deploy-prod:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      - integration-tests

      - test-skip-install-check

      - orb-tools/dev-promote-prod-from-commit-subject:
          orb-name: circleci/aws-cli
          context: orb-publishing
          add-pr-comment: true
          bot-token-variable: GHI_TOKEN
          bot-user: cpe-bot
          fail-if-semver-not-indicated: true
          publish-version-tag: true
          ssh-fingerprints: ed:dc:9c:fd:ab:7e:16:5b:28:9f:98:68:5f:80:82:dd
          filters:
            branches:
              only: master
          requires:
            - integration-tests
            - test-skip-install-check
