description: |
  Highly cached minimal Ubuntu docker designed for CircleCI with Python. 
parameters:
  python-version:
    description: >
      Select your python version or any of the available tags here: https://hub.docker.com/r/cimg/python
    type: string
    default: "3.8"

docker:
  - image: cimg/python:<<parameters.python-version>>
